//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://sandbox.coordinadora.com/agw/ws/guias/1.6/server.php")]
        public string Infraestructura_WsGenerarGuiasPruebas_JRpcServerSoapManagerService {
            get {
                return ((string)(this["Infraestructura_WsGenerarGuiasPruebas_JRpcServerSoapManagerService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://guias.coordinadora.com/ws/guias/1.6/server.php")]
        public string Infraestructura_WsGenerarGuiasReal_JRpcServerSoapManagerService {
            get {
                return ((string)(this["Infraestructura_WsGenerarGuiasReal_JRpcServerSoapManagerService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.120.81:7780/GTIntegrationMultiCia_Pruebas/ServiciosWeb/wsGenerarPl" +
            "ano.asmx")]
        public string Infraestructura_Ws_GT_Pruebas_wsGenerarPlano {
            get {
                return ((string)(this["Infraestructura_Ws_GT_Pruebas_wsGenerarPlano"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.120.81:7780/GTIntegrationMultiCia/ServiciosWeb/wsGenerarPlano.asmx" +
            "")]
        public string Infraestructura_Ws_GT_Real_wsGenerarPlano {
            get {
                return ((string)(this["Infraestructura_Ws_GT_Real_wsGenerarPlano"]));
            }
        }
    }
}
